---
# tasks file for vector-role
- name: Get vector distrib
  block:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
        mode: "0440"
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    name: ./vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: true
- name: Deploy config
  become: true
  ansible.builtin.template:
    src: vector.j2
    dest: /etc/vector/vector.yaml
    mode: "0644"
- name: Create systemd service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /lib/systemd/system/vector.service
    mode: "0644"
  notify: Start vector service
